version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    restart: always
    networks:
      - application
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    env_file:
      - ./.env
    networks:
      - application
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  db-migrate:
    container_name: db-migrate
    image: migrate/migrate
    networks:
      - application
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    command: [
      "-path",
      "/migrations",
      "-database",
      "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${SSL_MODE}",
      "up"
    ]
    links:
      - db


networks:
  application:

volumes:
  pgdata: